{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ include "postgres.username" . | quote }}
  password: {{ include "postgres.password" . | quote }}
{{- end }}
